/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnchorNavigation: typeof import('./src/components/AnchorNavigation.vue')['default']
    ApexChart: typeof import('./src/components/ApexChart.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu/index.vue')['default']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-next')['BCardFooter']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-next')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next')['BFormRadioGroup']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BProgress: typeof import('bootstrap-vue-next')['BProgress']
    BProgressBar: typeof import('bootstrap-vue-next')['BProgressBar']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTfoot: typeof import('bootstrap-vue-next')['BTfoot']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    ChoicesInput: typeof import('./src/components/ChoicesInput.vue')['default']
    ChoicesSelect: typeof import('./src/components/ChoicesSelect.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    DropFile: typeof import('./src/components/DropFile.vue')['default']
    DropFileBanner: typeof import('./src/components/DropFileBanner.vue')['default']
    FlatPicker: typeof import('./src/components/FlatPicker.vue')['default']
    GridJsTable: typeof import('./src/components/GridJsTable.vue')['default']
    InputMask: typeof import('./src/components/InputMask.vue')['default']
    JsVectorMap: typeof import('./src/components/JsVectorMap.vue')['default']
    LogoBox: typeof import('./src/components/LogoBox.vue')['default']
    MenuItem: typeof import('./src/components/AppMenu/MenuItem.vue')['default']
    MenuItemLink: typeof import('./src/components/AppMenu/MenuItemLink.vue')['default']
    MenuItemWithChildren: typeof import('./src/components/AppMenu/MenuItemWithChildren.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UIComponentCard: typeof import('./src/components/UIComponentCard.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
  }
}
