import type { EmailType, NavLinkType } from '@/views/apps/email/components/types'

export const emailData: EmailType[] = [
  {
    id: 'InboxChk1',
    sender: 'Daniel J. Olsen',
    subject: 'Lucas Kriebel (@Daniel J. Olsen) has sent you a direct message on Twitter!',
    message: '@Daniel J. Olsen - Very cool :) Nicklas, You have a new direct message.',
    date: '11:49 am',
    status: 'unread',
    isRead: false,
    isStarred: false,
    isImportant: true,
    isSent: false,
    isTrash: false,
    type: 'social',
    categories: ['social', 'important']
  },
  {
    id: 'InboxChk2',
    sender: 'Jack P. Roldan',
    subject: 'Images',
    message: '',
    attachType: 'image',
    attachments: ['IMG_201', 'IMG_202', 'IMG_203'],
    badge: '+5',
    date: 'Feb 21',
    status: 'read',
    isRead: true,
    isStarred: true,
    isImportant: true,
    isSent: true,
    isTrash: true,
    type: 'promotions',
    categories: ['promotions', 'starred', 'important', 'sent', 'trash']
  },
  {
    id: 'InboxChk3',
    sender: 'Betty C. Cox (11)',
    subject: 'Train/Bus',
    message: "Yes ok, great! I'm not stuck in Stockholm anymore, we're making progress.",
    date: 'Feb 19',
    status: 'read',
    isRead: true,
    isStarred: false,
    isImportant: false,
    isSent: false,
    isTrash: false,
    type: 'updates',
    categories: ['updates']
  },
  {
    id: 'InboxChk4',
    sender: 'Medium',
    subject: "This Week's Top Stories",
    message: "Our top pick for you on Medium this week The Man Who Destroyed America's Ego",
    date: 'Feb 28',
    status: 'unread',
    isRead: false,
    isStarred: false,
    isImportant: false,
    isSent: true,
    isTrash: true,
    type: 'forums',
    categories: ['forums', 'sent', 'trash']
  },
  {
    id: 'InboxChk5',
    sender: 'Death to Stock',
    subject: '(no subject)',
    message: '',
    attachType: 'pdf',
    attachments: ['dashboard.pdf', 'pages-data.pdf'],
    date: 'Feb 28',
    status: 'read',
    isRead: true,
    isStarred: true,
    isImportant: false,
    isSent: false,
    isTrash: false,
    type: 'social',
    categories: ['social', 'starred']
  },
  {
    id: 'InboxChk6',
    sender: 'Revibe',
    subject: '(no subject)',
    message: '',
    attachType: 'doc',
    attachments: ['doc1.doc', 'doc2.doc', 'doc3.doc', 'doc4.doc'],
    date: 'Feb 27',
    status: 'read',
    isRead: true,
    isStarred: false,
    isImportant: true,
    isSent: false,
    isTrash: true,
    type: 'promotions',
    categories: ['promotions', 'important', 'trash']
  },
  {
    id: 'InboxChk7',
    sender: 'Erik, me (5)',
    subject: 'Regarding our meeting',
    message: "That's great, see you on Thursday!",
    date: 'Feb 24',
    status: 'read',
    isRead: true,
    isStarred: true,
    isImportant: false,
    isSent: true,
    isTrash: false,
    type: 'social',
    categories: ['social', 'starred', 'sent']
  },
  {
    id: 'InboxChk8',
    sender: 'KanbanFlow',
    subject: "Task assigned: Clone ARP's website",
    message: 'You have been assigned a task by Alex@Work on the board Web.',
    date: 'Feb 24',
    status: 'read',
    isRead: true,
    isStarred: true,
    isImportant: false,
    isSent: true,
    isTrash: false,
    type: 'updates',
    categories: ['updates', 'starred', 'sent']
  },
  {
    id: 'InboxChk9',
    sender: 'Tobias Berggren',
    subject: "Let's go fishing!",
    message: "Hey, You wanna join me and Fred at the lake tomorrow? It'll be awesome.",
    date: 'Feb 23',
    status: 'read',
    isRead: true,
    isStarred: false,
    isImportant: true,
    isSent: true,
    isTrash: false,
    type: 'updates',
    categories: ['updates', 'important', 'sent']
  },
  {
    id: 'InboxChk10',
    sender: 'Charukaw, me (7)',
    subject: 'Hey man',
    message: "Nah man sorry i don't. Should i get it?",
    date: 'Feb 23',
    status: 'read',
    isRead: true,
    isStarred: true,
    isImportant: true,
    isSent: true,
    isTrash: false,
    type: 'forums',
    categories: ['forums', 'starred', 'important', 'sent']
  },
  {
    id: 'InboxChk11',
    sender: 'Stack Exchange',
    subject: '1 new items in your Stackexchange inbox',
    message: 'The following items were added to your Stack Exchange global inbox since you last checked it.',
    date: 'Feb 21',
    status: 'read',
    isRead: true,
    isStarred: true,
    isImportant: false,
    isSent: true,
    isTrash: true,
    type: 'social',
    categories: ['social', 'starred', 'sent', 'trash']
  },
  {
    id: 'InboxChk12',
    sender: 'Google Drive Team',
    subject: 'You can now use your storage in Google Drive',
    message: 'Hey Nicklas Sandell! Thank you for purchasing extra storage space in Google Drive.',
    date: 'Feb 20',
    status: 'read',
    isRead: true,
    isStarred: true,
    isImportant: false,
    isSent: false,
    isTrash: true,
    type: 'promotions',
    categories: ['promotions', 'starred', 'trash']
  },
  {
    id: 'InboxChk13',
    sender: 'Peter, me (3)',
    subject: 'Hello',
    message: 'Trip home from Colombo has been arranged, then Jenna will come get me from Stockholm. :)',
    date: 'Mar 6',
    status: 'read',
    isRead: true,
    isStarred: false,
    isImportant: true,
    isSent: true,
    isTrash: true,
    type: 'updates',
    categories: ['updates', 'important', 'sent', 'trash']
  },
  {
    id: 'InboxChk14',
    sender: 'me, Susanna (7)',
    subject: "Since you asked... and i'm inconceivably bored at the train station",
    message: "Alright thanks. I'll have to re-book that somehow, i'll get back to you.",
    date: 'Mar 6',
    status: 'read',
    isRead: true,
    isStarred: false,
    isImportant: false,
    isSent: false,
    isTrash: true,
    type: 'forums',
    categories: ['forums', 'trash']
  }
]

export const emailTabs: string[] = ['email-starred', 'email-draft', 'email-sent', 'email-trash', 'email-important', 'email-updates', 'email-social', 'email-promotion', 'email-forums']

export const navLinkData: NavLinkType[] = [
  { title: 'Inbox', link: 'email-inbox', category: '', badge: '7', badgeVariant: 'danger', icon: 'bxs-inbox' },
  { title: 'Starred', link: 'email-starred', category: 'isStarred', icon: 'bx-star' },
  { title: 'Draft', link: 'email-draft', category: '', badge: '32', badgeVariant: 'info', icon: 'bxs-file' },
  { title: 'Sent Mail', link: 'email-sent', category: 'isSent', icon: ' bx-send' },
  { title: 'Trash Mail', link: 'email-trash', category: 'isTrash', icon: 'bx-trash' },
  { title: 'Important', link: 'email-important', category: 'isImportant', icon: 'bx-tag' },
  { title: 'Labels', isTitle: true },
  { title: 'Updates', link: 'email-updates', category: 'updates', isLabel: true, variant: 'info' },
  { title: 'Social', link: 'email-social', category: 'social', isLabel: true, variant: 'primary' },
  { title: 'Promotions', link: 'email-promotion', category: 'promotions', isLabel: true, variant: 'secondary' },
  { title: 'Forums', link: 'email-forums', category: 'forums', isLabel: true, variant: 'success' }
]
